# Generated by Django 5.0.1 on 2024-02-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-time_create'], name='task_task_time_cr_eb3927_idx'),
        ),
    ]
